### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by xbony2** [elifoster/atom-minetweaker#1]
The pound/hashtag/whatever works as a one lined comment in ZenScript. However, your atom editor seems to not know this.

**Comment by elifoster** [comment]
@xbony2 This is the first time I've heard it called ZenScript. Should I change the name of the language to ZenScript?

**Comment by xbony2** [comment]
ZenScript is the scripting engine for MineTweaker. It's created specifically for MT, so I wouldn't.

**Comment by elifoster** [comment]
Alright then.
