### ISSUE TITLE
Minetweaker syntax Support for Notpad ++

### ISSUE THREAD

**Issue by Dream-Master** [elifoster/atom-minetweaker#3]
Is it possible to add or enable MineTweaker syntax support for Notepad ++

**Comment by Voidi** [comment]
http://lmgtfy.com/?q=MineTweaker+syntax+support+for+Notepad+%2B%2B

https://github.com/ljfa-ag/npp-minetweaker

**Comment by Dream-Master** [comment]
Thanks. I googled it all ready but  I didn't find it. Thanks.

**Comment by elifoster** [comment]
Yeah, I also can't test anything for NP++ :P

**Comment by Dream-Master** [comment]
Works good I test it already.
