### ISSUE TITLE
Is broken

### ISSUE THREAD

**Issue by xbony2** [elifoster/atom-minetweaker#4]
I think this package might be broken. It's installed, but it's not even listed as a grammar :P

**Comment by elifoster** [comment]
I know. The Atom API changed drastically and i haven't got a chance to fix it fully yet.

**Comment by ghost** [comment]
![meh](http://i.nentify.me/wHL36wAH.png)

Got this far, not familiar enough with RegEx to do much more really. Maybe it will help. v0v Couldn't get your RegEx from before to work either.

My repo: https://github.com/Nentify/atom-minetweaker

Edit: The snippets seem to work fine.

Edit 2: Also, I was using the naming conventions here which automatically apply styles and can be themed: https://manual.macromates.com/en/language_grammars

**Comment by ghost** [comment]
![colour](http://i.nentify.me/auQYGLHL.png)

I've got some colour back, but I'm not sure how you want/expect it to look. :P Got any screenies from before?

**Comment by elifoster** [comment]
That's pretty damn close to what it was before. No I don't, unfortunately.

**Comment by ghost** [comment]
You can do what you want with my code really, the RegEx is driving me insane. :P

**Comment by elifoster** [comment]
Could you submit a PR?

**Comment by Codingale** [comment]
I think this is broken again isn't it? I'm not sure if it's just my install as I'm new with Atom. Do I need to do more than just install the package?

**Comment by elifoster** [comment]
No you shouldnt need to do more.

**Comment by Codingale** [comment]
Mods keywords are not highlighted eg: `mods.thermalexpansion.Furnace.addRecipe` 

`recipes.addShapeless`, `recipes.addShaped` and `print` are highlighted but only the direct functions. Nothing like `<ore:dustCoal>` is highlighted though or keywords such as `short` and `as` etc

**Comment by Codingale** [comment]
Here's the current formatting vs a Notepad++ version I modified a bit:

http://imgur.com/a/FX7vv

**Comment by elifoster** [comment]
Huh. The spec looks fine for me. What version of Atom are you running? I'm currently using 1.9.8.

**Comment by elifoster** [comment]
I just checked. 1.9.8 is the latest version of Atom. Try updating and see if that works :+1:

**Comment by Codingale** [comment]
I'm using `One Dark` as my Atom Syntax theme, and `Atom Dark` as the main theme.
Running version 1.9.8 with a few plugins.
![atom](https://cloud.githubusercontent.com/assets/6324853/17641196/c430a0c0-60e3-11e6-8335-1c8178fad31b.png)

**Comment by elifoster** [comment]
With those themes, it still appears to be working as expected on my end.

**Comment by Codingale** [comment]
What could be the issue then? I'm not entirely sure.

**Comment by elifoster** [comment]
Honestly I have no clue :confused:

**Comment by elifoster** [comment]
Actually, I haven't asked so I probably should, are you sure that it is using MineTweaker as the language? You can see it in the corner next to the encoding and package update notifier.

**Comment by elifoster** [comment]
AHA! I figured it out. Kinda. Something is messed up with the mods grammar. It actually makes sense that I would have missed this, because it is not included in the spec.

See: #7 for further discussion.
